### ISSUE TITLE
Mapa mental -Sandra Salgado Pérez 1BS

### ISSUE THREAD

**Issue by Sandrasalgado** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Sandrasalgado#1]
![Sandrasalgadopérez_1BS-220826233925](https://user-images.githubusercontent.com/112215053/187833351-f55bc696-456c-4b69-8362-eab383bf41b6.jpg)

**Comment by Daisy-GonzalezLita12** [comment]
19

**Comment by josealfredo79** [comment]
La calificación debe ser entre 0 y 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
